name: Storybook
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install and Build 🔧
        run:
          npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: docs
